export const MOCK_JOBS = [
  {
    id: "mock-1",
    title: "Staff Reporter, Politics",
    company: "The New York Times",
    location: "New York, NY",
    url: "https://www.nytco.com/careers/",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-01",
  },
  {
    id: "mock-2",
    title: "Investigative Reporter",
    company: "ProPublica",
    location: "New York, NY",
    url: "https://job-boards.greenhouse.io/propublica",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-05",
  },
  {
    id: "mock-3",
    title: "Data Journalist",
    company: "Axios",
    location: "Washington, DC",
    url: "https://job-boards.greenhouse.io/axios",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-10",
  },
  {
    id: "mock-4",
    title: "Breaking News Reporter",
    company: "Politico",
    location: "Arlington, VA",
    url: "https://politico.wd108.myworkdayjobs.com/en-US/politico/",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-12",
  },
  {
    id: "mock-5",
    title: "Senior Editor, Health",
    company: "Semafor",
    location: "Washington, DC",
    url: "https://job-boards.greenhouse.io/semafor/",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-14",
  },
  {
    id: "mock-6",
    title: "Video Producer",
    company: "Bloomberg Industry Group",
    location: "Washington, DC",
    url: "https://bloomberg.wd1.myworkdayjobs.com/en-US/Bloombergindustrygroup_External_Career_Site",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-15",
  },
  {
    id: "mock-7",
    title: "Criminal Justice Reporter",
    company: "The Marshall Project",
    location: "Remote",
    url: "https://www.themarshallproject.org/jobs",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-16",
  },
  {
    id: "mock-8",
    title: "Newsletter Writer",
    company: "City Cast",
    location: "Remote",
    url: "https://apply.workable.com/city-cast/",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-17",
  },
  {
    id: "mock-9",
    title: "Local Reporter",
    company: "The Baltimore Banner",
    location: "Baltimore, MD",
    url: "https://job-boards.greenhouse.io/thebaltimorebanner",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-18",
  },
  {
    id: "mock-10",
    title: "Sports Reporter",
    company: "Bleacher Report",
    location: "New York, NY",
    url: "https://careers.wbd.com/global/en/search-results",
    updated_at: null,
    updatedAt: new Date().toISOString(),
    first_published: "2026-02-19",
  },
];
